src/minZdrav/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import re_path as url
from logRegisPages.views import  registration, activate, user_login, user_logout, CustomPasswordResetView, CustomPasswordResetConfirmView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from news.views import post_new
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('static_pages.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    
    
]
urlpatterns += i18n_patterns(
    path('news/', include('news.urls')),
    path('new-news/', post_new, name = 'new_new'),
    path('med-services/', include('medServices.urls')),
    path('rules/', include('info_page.urls')),
    path('viewSovet/', include('viewSovet.urls')),
    path('contacts/', include('contact_pages.urls')),
    path('histories/', include('history_legends.urls')),
    path('ceo-info/', include('ceoInfo.urls')),
    path('vacancies/', include('vacancies.urls')),
    path('organization-structure/', include('orgStruct.urls')),
    path('rights-acts/', include('ProvActs.urls')),
    path('workers-info/', include('workersInfo.urls')),
    path('anticorruption/', include('antiCorruptions.urls')),
    path('about/', include('aboutPage.urls')),    
    path('reviews/', include('reviewsBlog.urls')),
    path('advertisement/', include('advertisement.urls')),
    path('login/', user_login, name = 'login'),
    path('logout/', user_logout, name = 'logout'),
    path('registration/', registration, name = 'registr'),
    path('password-reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/', activate, name='activate'),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/news/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.post_list, name = 'news'),
    path('<int:pid>/', views.post_detail, name = 'new_detail'),
    # path('new/', views.post_new, name='new_new'),
    path('<int:pid>/edit/', views.post_edit, name='new_edit'),
]

src/news/models.py
from django.db import models
import os
from django.utils import timezone
from logRegisPages.models import CustomUser

class Post(models.Model):
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    title = models.CharField(max_length = 128, verbose_name='Title')
    date = models.DateTimeField(auto_now=timezone.now)
    content = models.TextField(verbose_name='Content')

    def __str__(self) -> str:
        return f'{self.title}: {self.content} ({self.date})'
# Create your models here.

class PostAttachment(models.Model):
    file = models.FileField(upload_to='images/')
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    type = models.CharField(max_length = 6, blank=True, null=True )

    def save(self, *args, **kwargs):
        file_extension = self.file.name.split('.')[-1].lower()
        print(file_extension)
        if file_extension in ['jpg', 'jpeg', 'png', 'gif']:
            self.type = 'img'
        else:
            self.type = 'doc'
        
        super().save(*args, **kwargs)

src/templates/reviewsPages/add_answer.html
{% extends 'base.html' %}
{% load i18n%}
{% block content %}

<div class="form-card">
    <h1>{%trans 'Ответ на отзыв'%}</h1>
    <p class="review-text"><b>{%trans 'Отзыв от'%} {{ review.author }}:</b> <br>{{ review.review }}</p>

    <form method="post" class="login-card">
        {% csrf_token %}
        <label for="id_answer">{%trans 'Ответ отзыв'%}:</label>
        {{ form.answer }}
        <button type="submit" class="btn">{%trans 'Отправить ответ'%}</button>
    </form>
</div>
{% endblock %}

src/templates/reviewsPages/add_review.html
{% extends 'base.html' %}
{%load i18n%}
{% block content %}
<div class="form-card">
    <form method="post" class="login-card">
        {% csrf_token %}
        <label for="id_author">{%trans 'Ваше имя'%}:</label>
        {{ form.author }}
        <label for="id_IIN">{%trans 'ИИН'%}:</label>
        {{ form.IIN }}
        <label for="id_review">{%trans 'Ваш отзыв'%}:</label>
        {{ form.review }}
        
        <button class="btn" type="submit">{%trans 'Отправить отзыв'%}</button>
    </form>
</div>
{% endblock %}

src/templates/reviewsPages/reviews_list.html
{% extends 'base.html' %}
{%load i18n%}
{% block content %}
<div class="content-split">
    <div class="navigation">
        <a href="{% url 'viewSovet'%}">{% trans 'Наблюдательный совет' %}</a>
        <a href="{% url 'histories'%}">{% trans 'История' %}</a>
        <a href="{% url 'ceo-info' %}">{% trans 'Руководитель' %}</a>
        <a href="{% url 'vacancies'%}">{% trans 'Вакансии' %}</a>
        <a href="{% url 'orgStruct'%}">{% trans 'Организационная структура' %}</a>
        <a href="{% url 'reviews'%}" class="selected">{% trans 'Отзывы' %}</a>
        <a href="{% url 'contacts'%}">{% trans 'Контакты' %}</a>
        <a href="{% url 'rights-acts'%}">{% trans 'Правовые акты' %}</a>
        <a href="{% url 'workers-info'%}">{% trans 'Сведения о работниках' %}</a>
        <a href="{% url 'antiCor'%}">{% trans 'Противодействие коррупции' %}</a>
        <a href="{% url 'ads'%}">{% trans 'Протокол итогов' %}</a>
    </div>
    <div >
        <div class="new-review">
            <p class="Title">{%trans 'Отзывы'%}</p>
            <a href="{% url 'add-review' %}" class="btn">{%trans 'Оставить Отзыв'%}</a>
        </div>
        {% for review in reviews %}
            <div class="new-frame">
                <div class="frame-header-block">
                    <p><b>{{review.author}}</b></p>
                </div>
                <hr>
                <span class="frame-content">{{review.review}} </span>
                <div class="frame-btn">
                    <p class="date">{{review.date}}</p>
                    {% if not review.answer %}
                        {% if  user.is_authenticated and user.is_staff %}
                            <a href="{% url 'add-answer' rid=review.pk %}" class="btn">{%trans 'Ответить'%}</a>
                        {% endif %}
                    {% endif %}
                </div>
                
                {% for answer in review.answer %}
                    <div class="new-frame">
                        <span class="frame-content">{%trans 'Ответ'%} : {{answer.answer}} </span>
                        <div class="frame-btn">
                            <p class="date">{{answer.date}}</p>
                        </div>
                    </div>
                {% endfor %}
                
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}