src/minZdrav/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import re_path as url
from logRegisPages.views import  registration, activate, user_login, user_logout, CustomPasswordResetView, CustomPasswordResetConfirmView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from news.views import post_new
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('static_pages.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    
    
]
urlpatterns += i18n_patterns(
    path('news/', include('news.urls')),
    path('new-news/', post_new, name = 'new_new'),
    path('med-services/', include('medServices.urls')),
    path('rules/', include('info_page.urls')),
    path('viewSovet/', include('viewSovet.urls')),
    path('contacts/', include('contact_pages.urls')),
    path('histories/', include('history_legends.urls')),
    path('ceo-info/', include('ceoInfo.urls')),
    path('vacancies/', include('vacancies.urls')),
    path('organization-structure/', include('orgStruct.urls')),
    path('rights-acts/', include('ProvActs.urls')),
    path('workers-info/', include('workersInfo.urls')),
    path('anticorruption/', include('antiCorruptions.urls')),
    path('about/', include('aboutPage.urls')),    
    path('reviews/', include('reviewsBlog.urls')),
    path('advertisement/', include('advertisement.urls')),
    path('login/', user_login, name = 'login'),
    path('logout/', user_logout, name = 'logout'),
    path('registration/', registration, name = 'registr'),
    path('password-reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/', activate, name='activate'),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/news/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.post_list, name = 'news'),
    path('<int:pid>/', views.post_detail, name = 'new_detail'),
    # path('new/', views.post_new, name='new_new'),
    path('<int:pid>/edit/', views.post_edit, name='new_edit'),
]

src/news/models.py
from django.db import models
import os
from django.utils import timezone
from logRegisPages.models import CustomUser

class Post(models.Model):
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    title = models.CharField(max_length = 128, verbose_name='Title')
    date = models.DateTimeField(auto_now=timezone.now)
    content = models.TextField(verbose_name='Content')

    def __str__(self) -> str:
        return f'{self.title}: {self.content} ({self.date})'
# Create your models here.

class PostAttachment(models.Model):
    file = models.FileField(upload_to='images/')
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    type = models.CharField(max_length = 6, blank=True, null=True )

    def save(self, *args, **kwargs):
        file_extension = self.file.name.split('.')[-1].lower()
        print(file_extension)
        if file_extension in ['jpg', 'jpeg', 'png', 'gif']:
            self.type = 'img'
        else:
            self.type = 'doc'
        
        super().save(*args, **kwargs)

src/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load i18n%}
{% block content %}
<div class="content-inner">
    <div class="new-frame">
        <h1 class="fame-header">{{post.title}}</h1>
        <p style="font-weight: 300; font-size: 15px;">{%trans 'Опубликовано'%}: <b>{{post.author.name}}</b></p>
        <p class="big_content">{{post.content}}</p>
        {% for att in attachments %}
        {% if att.type == 'img' %}
            <div class="big_pic">
                <img src="/media/{{att.file}}" alt="" width="100%">
            </div>
        {% else %}
            <div class="documents">
                <iframe src="/media/{{att.file}}"></iframe>
            </div>
        {% endif %}
        {% endfor %}
        <p class="date mg-b">{{post.date}}</p>
    </div>
    <div class="comments">
    {% for comms in comments %}
        <div class="comment-card">
            <p class="comment-username">{{comms.author}}</p>
            <p class="comment-time">{{comms.time_stamp}}</p>
            <p class="comment-body">{{comms.content}}</p> 
        </div>
        {% endfor %}
    </div>
</div> 
{% endblock %}

src/templates/posts/post_list.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
    <div class="news-plates">
        <div class="new-review">
            <h1>{% trans 'Новости' %}</h1>
                {% if  user.is_authenticated and user.is_staff %}
                    <a href = "{% url 'new_new' %}" class="btn"> {% trans 'Добавить объявление' %}</a>
                {% endif %}
        </div>
        {% for post in post_list %}
        <div class="new-frame">
            <div class="frame-header-block">
                <span class="frame-header mg-t">{{post.title}}</span>
                
                <p style="font-weight: 300; font-size: 15px;"><i>{%trans 'Опубликовано'%}: </i><b>{{post.author.name}}</b></p>
            </div>
            <hr>
            <span class="frame-content">{{post.content}} </span>
            <div class="frame-btn">
                <p class="date">{{post.date}}</p>
                <a href="{% url 'new_detail' pid=post.pk %}" class="btn">{%trans 'Читать далее'%}...</a>
            </div>
            
        </div>
        
    {% endfor %}
    </div>
{% endblock %}

src/templates/posts/post_new.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
    <div class="form-card">
        <h1>{%trans 'Новое объявление'%}</h1>
        <form method="post" enctype="multipart/form-data" class="login-card">
            {% csrf_token %}
            <label for="id_title">{%trans 'Заголовок'%}:</label>
            {{ form.title }}
            <label for="id_content">{%trans 'Информация'%}:</label>
            {{ form.content }}
            <label for="file-upload-input" class="btn mg-b custom-file-upload" >{%trans 'Выбрать файл'%}</label>
            <div style="display: none;">
                {{ form.images }}
            </div>

            <p id="selected-files" ></p>
            {{ attachments.as_p }}
            <button type="submit" class="btn">{%trans 'Опубликовать'%}</button>
        </form>
    </div>
    <script src="../static/script.js"></script>
{% endblock %}